# apiVersion: networking.k8s.io/v1beta1 ## this is older version 1.6 below
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kroki
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kroki
            port:
              number: 8000
